### Register User
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Kaushal",
  "email": "kaushal@gmail.com",
  "password": "123456"
}

###

### Login User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "kaushal@gmail.com",
  "password": "123456"
}

###

### Get User Profile (JWT Protected)
GET http://localhost:3000/users/profile
Authorization: Bearer <JWT_TOKEN>

###

### Update User Profile (JWT Protected)
PUT http://localhost:3000/users/profile
Authorization: Bearer <JWT_TOKEN>
Content-Type: application/json

{
  "name": "Kaushal Updated",
  "password": "newpass123"
}

###

### Get All Users (Admin Only)
GET http://localhost:3000/users
Authorization: Bearer <JWT_TOKEN>

###

### Soft Delete User (JWT Protected)
DELETE http://localhost:3000/users/USER_ID
Authorization: Bearer <JWT_TOKEN>

###

### Hard Delete User
DELETE http://localhost:3000/users/hard/USER_ID
Authorization: Bearer <JWT_TOKEN>

###

### Search Users by Name
GET http://localhost:3000/users/search/name?name=ka
Authorization: Bearer <JWT_TOKEN>

###

### Search Users by Email
GET http://localhost:3000/users/search/email?email=gmail
Authorization: Bearer <JWT_TOKEN>

###

### Paginate Users (5 per page)
GET http://localhost:3000/users/paginate?page=1
Authorization: Bearer <JWT_TOKEN>
